name: "Build and populate cache"
on:
  pull_request:
  push:
    branches:
      - main
      - master
  #schedule:
    # rebuild everyday at 2:51
    # TIP: Choose a random time here so not all repositories are build at once:
    # https://www.random.org/clock-times/?num=1&earliest=01%3A00&latest=08%3A00&interval=5&format=html&rnd=new
    #- cron:  '51 2 * * *'
jobs:
  tests:
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
        nixPath:
          - nixpkgs=channel:nixos-unstable
          - nixpkgs=channel:nixpkgs-unstable
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v23
      with:
        nix_path: "${{ matrix.nixPath }}"
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Setup cachix
      uses: cachix/cachix-action@v12
      with:
        name: cryolitia
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Check evaluation
      run: |
        nix-env -f . -qa \* --meta --xml \
          --allowed-uris https://static.rust-lang.org \
          --option restrict-eval true \
          --option allow-import-from-derivation true \
          --drv-path --show-trace \
          -I nixpkgs=$(nix-instantiate --find-file nixpkgs) \
          -I $PWD
    - name: Build x86_64 nix packages
      if: ${{ matrix.arch == 'x86_64' }}
      run: nix shell -f '<nixpkgs>' nix-build-uncached -c nix-build-uncached ci.nix -A cacheOutputs
    - name: Build aarch64 nix packages
      if: ${{ matrix.arch == 'aarch64' }}
      run: nix shell -f '<nixpkgs>' nix-build-uncached -c nix-build-uncached ci.nix --arg crossSystem '(import <nixpkgs.lib>).systems.examples.aarch64-multiplatform' -A cacheOutputs
    - name: Trigger NUR update
      run: curl -XPOST "https://nur-update.nix-community.org/update?repo=Cryolitia"
